services:
  jenkins:

    image: zng155/jenkins:latest
    container_name: jenkins
    pull_policy: always
    user: root

    ports:
      - 8081:8080

    volumes:
      - ./jenkins:/var/jenkins_home
      # - //./pipe/docker_engine:/var/run/docker.sock
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/local/bin/docker:/usr/local/bin/docker
